export const tasks = [
    {
        "id": 1,
        "classroom_id": 3,
        "title": "Optio et vero voluptas suscipit ab consequatur quia.",
        "content": "Dolore repudiandae velit alias fugiat. Ut ut autem ipsum unde commodi aut est. Iste eum quod impedit est magni. Optio esse repellat deleniti est. Deserunt animi dolores ut quam molestias minima.",
        "due_date": "2024-12-16 18:34:25",
        "type": "assignment",
        "created_at": "2024-12-13T17:12:17.000000Z",
        "updated_at": "2024-12-13T17:12:17.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 3,
            "user_id": 9,
            "identifier_code": "CLASS-hlwpj",
            "class_name": "qui",
            "description": "Et voluptates quisquam optio officiis corrupti ea voluptates. Esse error quis voluptas et et. Iusto qui cumque numquam sed optio nesciunt velit corporis. Nihil molestias illum dignissimos.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php385.tmp",
            "bg_tw_class": "bg-orange-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:16.000000Z",
            "updated_at": "2024-12-13T17:12:16.000000Z"
        }
    },
    {
        "id": 2,
        "classroom_id": 4,
        "title": "Nam similique illo est.",
        "content": "Architecto eligendi blanditiis velit dolorem sequi architecto. Nihil fugiat qui aliquam molestiae sunt sunt. Non magnam veniam cupiditate in nisi consequatur.",
        "due_date": "2024-12-28 18:23:22",
        "type": "assignment",
        "created_at": "2024-12-13T17:12:17.000000Z",
        "updated_at": "2024-12-13T17:12:17.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 4,
            "user_id": 10,
            "identifier_code": "CLASS-gfdxx",
            "class_name": "sunt",
            "description": "Sunt et error sit laudantium vel natus nostrum. Minima nisi id sequi exercitationem. Repudiandae impedit accusantium vel error dolores.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php4ED.tmp",
            "bg_tw_class": "bg-rose-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:16.000000Z",
            "updated_at": "2024-12-13T17:12:16.000000Z"
        }
    },
    {
        "id": 3,
        "classroom_id": 5,
        "title": "Aperiam inventore enim ab quaerat fugiat laboriosam.",
        "content": "Unde voluptatibus enim in. Voluptates a possimus laboriosam et debitis quod. Accusamus aliquam perferendis et mollitia qui reprehenderit quia quis. Vero vitae ducimus voluptatibus deleniti similique.",
        "due_date": "2025-01-10 07:40:06",
        "type": "assignment",
        "created_at": "2024-12-13T17:12:17.000000Z",
        "updated_at": "2024-12-13T17:12:17.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 5,
            "user_id": 11,
            "identifier_code": "CLASS-indvo",
            "class_name": "quo",
            "description": "Voluptatem magni itaque non et voluptate. Voluptas doloribus nisi eos eaque aperiam. Qui voluptatem iste maiores vitae et voluptatum. Aut distinctio vel ad soluta perferendis est velit.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php636.tmp",
            "bg_tw_class": "bg-green-600",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:17.000000Z",
            "updated_at": "2024-12-13T17:12:17.000000Z"
        }
    },
    {
        "id": 4,
        "classroom_id": 6,
        "title": "Nulla enim repellat voluptate alias illo asperiores veritatis.",
        "content": "Eos quidem repellat qui aut qui sunt. Unde facere magnam quo voluptatem ipsa magnam ratione omnis. Id ipsum voluptate iste debitis et deleniti. Aut laborum accusamus et nostrum voluptas.",
        "due_date": "2024-12-29 02:48:52",
        "type": "assignment",
        "created_at": "2024-12-13T17:12:17.000000Z",
        "updated_at": "2024-12-13T17:12:17.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 6,
            "user_id": 12,
            "identifier_code": "CLASS-jolls",
            "class_name": "quod",
            "description": "Minus autem ex at sit repudiandae. Ab voluptatem laudantium in perferendis ut deserunt. Sapiente sit quo cum at accusamus itaque. Ut sed provident optio beatae.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php7AE.tmp",
            "bg_tw_class": "bg-rose-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:17.000000Z",
            "updated_at": "2024-12-13T17:12:17.000000Z"
        }
    },
    {
        "id": 5,
        "classroom_id": 7,
        "title": "Iste vel nihil occaecati eveniet amet laboriosam dolorum qui.",
        "content": "Impedit minus modi laboriosam dolorum iusto est ut. Et minus ut ullam sit deleniti. Qui vel nemo ipsam consequatur repellendus.",
        "due_date": "2024-12-18 03:18:21",
        "type": "assignment",
        "created_at": "2024-12-13T17:12:17.000000Z",
        "updated_at": "2024-12-13T17:12:17.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 7,
            "user_id": 13,
            "identifier_code": "CLASS-zklyq",
            "class_name": "aut",
            "description": "Quia voluptatem enim et. Omnis est magni placeat. Ut voluptas excepturi doloremque qui quia eos nihil deleniti.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php8E8.tmp",
            "bg_tw_class": "bg-blue-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:17.000000Z",
            "updated_at": "2024-12-13T17:12:17.000000Z"
        }
    },
    {
        "id": 6,
        "classroom_id": 8,
        "title": "Libero rerum nostrum et quasi aut culpa.",
        "content": "Et nobis beatae eligendi vitae voluptatem in voluptas. Et dolore ut rerum omnis nesciunt omnis. Animi sint voluptatem at accusantium culpa pariatur sed. Aut explicabo earum dolor laboriosam ut.",
        "due_date": "2024-12-27 01:56:09",
        "type": "material",
        "created_at": "2024-12-13T17:12:19.000000Z",
        "updated_at": "2024-12-13T17:12:19.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 8,
            "user_id": 14,
            "identifier_code": "CLASS-cldiz",
            "class_name": "consequatur",
            "description": "Ipsa iusto velit consequatur minima. Repellendus recusandae autem nemo cupiditate molestiae. Laborum qui qui nesciunt esse molestiae eligendi. Omnis placeat ratione fuga ipsam impedit.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\phpA41.tmp",
            "bg_tw_class": "bg-rose-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:18.000000Z",
            "updated_at": "2024-12-13T17:12:18.000000Z"
        }
    },
    {
        "id": 7,
        "classroom_id": 9,
        "title": "Eum ea qui odit dolores sunt minima aperiam.",
        "content": "Suscipit quis aut fugiat doloribus ut enim eligendi. Est natus molestiae eum perspiciatis. Molestiae tempora enim aliquam quia placeat est. Dolor eum totam qui quis eum expedita. Et reiciendis unde est aut temporibus et ut ratione.",
        "due_date": "2024-12-21 16:04:37",
        "type": "material",
        "created_at": "2024-12-13T17:12:19.000000Z",
        "updated_at": "2024-12-13T17:12:19.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 9,
            "user_id": 15,
            "identifier_code": "CLASS-newho",
            "class_name": "exercitationem",
            "description": "Possimus similique velit illum aut magni. Cumque et aut vitae est iure inventore. Molestiae dolores dicta et temporibus quia qui itaque quis. Repudiandae sequi eos distinctio voluptas.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\phpB7A.tmp",
            "bg_tw_class": "bg-rose-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:18.000000Z",
            "updated_at": "2024-12-13T17:12:18.000000Z"
        }
    },
    {
        "id": 8,
        "classroom_id": 10,
        "title": "Et et iste aut harum.",
        "content": "Cum occaecati facilis qui sit. Assumenda dolore dignissimos dolor est quidem natus. Sint eum reiciendis aut laborum accusantium voluptas aperiam fuga.",
        "due_date": "2025-01-08 00:09:53",
        "type": "material",
        "created_at": "2024-12-13T17:12:19.000000Z",
        "updated_at": "2024-12-13T17:12:19.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 10,
            "user_id": 16,
            "identifier_code": "CLASS-sutik",
            "class_name": "consequatur",
            "description": "Odio facere molestiae facilis sit. Rerum cumque magni doloribus. Ea nam repellat minus et quia sit nihil. Mollitia aperiam et sint aut.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\phpCB4.tmp",
            "bg_tw_class": "bg-orange-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:18.000000Z",
            "updated_at": "2024-12-13T17:12:18.000000Z"
        }
    },
    {
        "id": 9,
        "classroom_id": 11,
        "title": "Qui qui dolores dolorem saepe.",
        "content": "Labore officiis quasi odit qui architecto qui. Nihil modi sunt recusandae quibusdam blanditiis. Necessitatibus sit a ipsum repellat autem eveniet sed. Officia ducimus nobis incidunt labore perferendis rerum.",
        "due_date": "2025-01-04 15:29:38",
        "type": "material",
        "created_at": "2024-12-13T17:12:19.000000Z",
        "updated_at": "2024-12-13T17:12:19.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 11,
            "user_id": 17,
            "identifier_code": "CLASS-bzmnh",
            "class_name": "ducimus",
            "description": "Suscipit pariatur illo in iusto ut omnis magni. Autem reprehenderit laborum itaque ut voluptatibus.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\phpDFD.tmp",
            "bg_tw_class": "bg-orange-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:19.000000Z",
            "updated_at": "2024-12-13T17:12:19.000000Z"
        }
    },
    {
        "id": 10,
        "classroom_id": 12,
        "title": "Sit rerum aliquid sed quam aperiam omnis dolorem.",
        "content": "Qui asperiores modi corrupti corrupti repellat odit distinctio qui. Iusto deleniti hic cumque aut et soluta delectus expedita. Rerum iste ipsam deleniti dolorem laudantium voluptas. Qui aut porro consequatur commodi voluptatem debitis. Laudantium est qui velit consequatur facere minus.",
        "due_date": "2024-12-14 08:52:06",
        "type": "material",
        "created_at": "2024-12-13T17:12:19.000000Z",
        "updated_at": "2024-12-13T17:12:19.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 12,
            "user_id": 18,
            "identifier_code": "CLASS-cxitm",
            "class_name": "velit",
            "description": "Aliquid consequatur sit veritatis quam. Non aliquid libero nihil tempora tempora. Illum sunt aut et velit ut. Molestiae qui est commodi sit sint accusantium est.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\phpF36.tmp",
            "bg_tw_class": "bg-orange-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:19.000000Z",
            "updated_at": "2024-12-13T17:12:19.000000Z"
        }
    },
    {
        "id": 11,
        "classroom_id": 13,
        "title": "Dolor omnis illum voluptas est.",
        "content": "Aliquam assumenda consequatur sed consequuntur sit numquam. Voluptatem voluptatem dolorum cumque voluptas qui ratione. Officiis et cumque est cumque quaerat.",
        "due_date": "2024-12-16 13:37:39",
        "type": "announcement",
        "created_at": "2024-12-13T17:12:21.000000Z",
        "updated_at": "2024-12-13T17:12:21.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 13,
            "user_id": 19,
            "identifier_code": "CLASS-sxqvn",
            "class_name": "dolor",
            "description": "Ab numquam illo maxime ut ut. Sunt rerum cupiditate nostrum consequatur error quo tempore similique. Distinctio voluptatibus et iure nulla quod voluptas aut est.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php107F.tmp",
            "bg_tw_class": "bg-rose-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:19.000000Z",
            "updated_at": "2024-12-13T17:12:19.000000Z"
        }
    },
    {
        "id": 12,
        "classroom_id": 14,
        "title": "Corrupti itaque laudantium aut culpa.",
        "content": "Fugit ut perferendis placeat dolorem doloremque expedita aliquam. Et sint quia porro dolorem velit eos cumque. Dicta suscipit qui doloribus eos eius tenetur pariatur. Non doloribus vitae voluptas nulla reprehenderit eligendi.",
        "due_date": "2024-12-22 18:02:32",
        "type": "announcement",
        "created_at": "2024-12-13T17:12:21.000000Z",
        "updated_at": "2024-12-13T17:12:21.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 14,
            "user_id": 20,
            "identifier_code": "CLASS-ovjhf",
            "class_name": "doloribus",
            "description": "Blanditiis ea laborum nihil provident. Dicta libero dolorem enim consequatur voluptatem blanditiis eum. Omnis quas suscipit provident maiores nemo suscipit.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php11B9.tmp",
            "bg_tw_class": "bg-purple-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:20.000000Z",
            "updated_at": "2024-12-13T17:12:20.000000Z"
        }
    },
    {
        "id": 13,
        "classroom_id": 15,
        "title": "Iste minus velit et est eum ratione.",
        "content": "Suscipit maiores ut beatae molestias nihil. Et quibusdam delectus necessitatibus perferendis. Qui perferendis et est quibusdam rerum. Delectus quidem quae et.",
        "due_date": "2024-12-18 09:17:07",
        "type": "announcement",
        "created_at": "2024-12-13T17:12:21.000000Z",
        "updated_at": "2024-12-13T17:12:21.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 15,
            "user_id": 21,
            "identifier_code": "CLASS-ohfma",
            "class_name": "voluptatem",
            "description": "Sed voluptatem quia veniam voluptatum voluptatem non sunt. Ut corporis consectetur eum maxime doloremque. Quam incidunt a assumenda quos omnis officia laboriosam.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php12F2.tmp",
            "bg_tw_class": "bg-rose-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:20.000000Z",
            "updated_at": "2024-12-13T17:12:20.000000Z"
        }
    },
    {
        "id": 14,
        "classroom_id": 16,
        "title": "Magnam maiores occaecati a quidem voluptas et inventore.",
        "content": "Pariatur debitis nihil consectetur consequatur laboriosam sint ad molestiae. Quas et inventore eaque deleniti. Cum ut necessitatibus ut quia qui quidem totam.",
        "due_date": "2025-01-10 16:04:30",
        "type": "announcement",
        "created_at": "2024-12-13T17:12:21.000000Z",
        "updated_at": "2024-12-13T17:12:21.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 16,
            "user_id": 22,
            "identifier_code": "CLASS-kpgft",
            "class_name": "sit",
            "description": "Quas dolores dolores fugiat rerum asperiores amet. Minus modi temporibus libero error perspiciatis repudiandae. Dolorem ut reprehenderit repudiandae expedita autem dolor.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php142C.tmp",
            "bg_tw_class": "bg-orange-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:20.000000Z",
            "updated_at": "2024-12-13T17:12:20.000000Z"
        }
    },
    {
        "id": 15,
        "classroom_id": 17,
        "title": "Et inventore consequatur delectus quod adipisci ab.",
        "content": "Ut eum sint est quas est pariatur quasi est. Aut sint et consectetur et repudiandae assumenda nulla.",
        "due_date": "2024-12-31 20:43:38",
        "type": "announcement",
        "created_at": "2024-12-13T17:12:21.000000Z",
        "updated_at": "2024-12-13T17:12:21.000000Z",
        "answer_avg_point": null,
        "classroom": {
            "id": 17,
            "user_id": 23,
            "identifier_code": "CLASS-jcvzt",
            "class_name": "culpa",
            "description": "Officia sapiente sint consequatur quia. Reprehenderit mollitia qui minima alias dignissimos perferendis odit porro. Ea amet et inventore nostrum molestias. Est voluptatum sed aperiam laborum.",
            "background_image": "C:\\Users\\alulg\\AppData\\Local\\Temp\\php1575.tmp",
            "bg_tw_class": "bg-purple-500",
            "is_archived": 0,
            "created_at": "2024-12-13T17:12:21.000000Z",
            "updated_at": "2024-12-13T17:12:21.000000Z"
        }
    }
]